<div class="row">
    <div class="span12">
        <div class="page-header">
            <h1>New transaction</h1>
        </div>
        <form class="form-horizontal" method="post">
            <div class="control-group">
                <label class="control-label" for="inputFrom">From</label>
                <div class="controls">
                    <select name="from" id="inputFrom">
                        <? foreach ($accounts as $account): ?>
                            <option value="<?= $account->id ?>">
                                <?= $this->escapeHtml($account->number) ?>
                                (<?= $account->balance() ?>)
                            </option>
                        <? endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="control-group <? if(!empty($accountToError)) echo 'error' ?>">
                <label class="control-label" for="inputTo">To</label>
                <div class="controls">
                    <input name="to" type="text" id="inputTo">
                    <? if(!empty($accountToError)): ?>
                    <span class="help-inline">Wrong account number</span>
                    <? endif; ?>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputSum">Sum</label>
                <div class="controls">
                    <div class="input-append">
                        <input name="sum" type="text" id="inputSum" value="0.00">
                        <span class="add-on">RUB</span>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">Next</button>
                    <button type="button" class="btn" onclick="history.go(-1); return false;">Back</button>
                </div>
            </div>
        </form>
    </div>
</div>