<div class="row">
    <div class="span12">
        <div class="page-header">
            <h1>Change password</h1>
        </div>
        <? if(!empty($error)): ?>
        <div class="alert alert-error"><?= $this->escapeHtml($error) ?></div>
        <? endif; ?>
        <form class="form-horizontal" method="post">
            <div class="control-group <? if(!empty($oldPwdError)) echo 'error' ?>">
                <label class="control-label" for="inputOldPassword">Old password</label>
                <div class="controls">
                    <input type="password" name="oldPassword" id="inputOldPassword" autofocus="true">
                    <? if(!empty($oldPwdError)): ?>
                    <span class="help-inline">Wrong password</span>
                    <? endif; ?>
                </div>
            </div>
            <div class="control-group <? if(!empty($newPwdError)) echo 'error' ?>">
                <label class="control-label" for="inputNewPassword">New password</label>
                <div class="controls">
                    <input type="password" name="newPassword" id="inputNewPassword">
                    <? if(!empty($newPwdError)): ?>
                    <span class="help-inline">Can't be empty</span>
                    <? endif; ?>
                </div>
            </div>
            <div class="control-group <? if(!empty($confirmNewPwdError)) echo 'error' ?>">
                <label class="control-label" for="inputConfirmPassword">Confirm password</label>
                <div class="controls">
                    <input type="password" name="confirmPassword" id="inputConfirmPassword">
                    <? if(!empty($confirmNewPwdError)): ?>
                    <span class="help-inline">Wrong password</span>
                    <? endif; ?>
                </div>
            </div>
            <div class="control-group">
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">Change</button>
                    <button type="button" class="btn" onclick="history.go(-1); return false;">Back</button>
                </div>
            </div>
        </form>
    </div>
</div>