<div class="row">
    <div class="span12">
        <div class="page-header">
            <h1><?= $header ?></h1>
        </div>
        <div class="alert alert-error"><?= $message ?></div>
        <a class="btn" href="#" onclick="history.go(-1); return false;">
            <i class="icon-arrow-left"></i>
            Go back
        </a>

        <? if (isset($exception)) : ?>
            <pre style="margin-top: 20px;"><?= $this->escapeHtml($exception) ?></pre>
        <? endif; ?>

    </div>
</div>