<!DOCTYPE html>
<html>
    <head>
        <title>PHDays iBank</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
        <link href="/css/index.css" rel="stylesheet" media="screen">
    </head>
    <body>

        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-inner">
                    <div class="pull-right">
                            <ul class="nav">
                                <li>
                                    <a href="/index/switchInterface/">
                                        <i class="icon-repeat icon-white"></i>
                                        Switch to desktop version
                                    </a>
                                </li>
                            </ul>
                        </div>
                    <a class="brand" href="/">PHDays iBank</a>
                </div>
            </div>
            <?= $content ?>
        </div>

        <script src="/js/jquery-1.9.1.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
    </body>
</html>