<!DOCTYPE html>
<html>
    <head>
        <title>PHDays iBank</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="refresh" content="5">
        <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/css/index.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <div id="wrap">
            <div class="navbar navbar-fixed-top navbar-inverse">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="brand" href="/">PHDays iBank</a>
                    </div>
                </div>
            </div>
            <div class="container" style="padding-top: 40px;">
                <?= $content ?>
            </div>

            <div id="push"></div>
        </div>

        <div id="footer">
            <div class="container">
                <p class="muted credit">&copy; 2013 PHDays iBank</p>
            </div>
        </div>

        <script src="/js/jquery-1.9.1.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
    </body>
</html>